apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/ref/branch
      value: main
  target:
    kind: GitRepository
- patch: |-
    - op: replace
      path: /spec/values/replicaCount
      value: 2
  target:
    kind: HelmRelease
- patch: |-
    - op: replace
      path: /spec/path
      value: ./overlays/prod
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: ostock
    namespace: infra
- patch: |-
    - op: replace
      path: /spec/path
      value: ./prod/sops-age
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: sops-age
    namespace: infra