apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/ref/branch
        value: main
    target:
      kind: GitRepository
  - patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 2
    target:
      kind: HelmRelease
  - patch: |-
      - op: add
        path: /spec/tls/0/hosts/-
        value: jcr.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: keycloak.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: oss.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: ostockng.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: ostockapi.nguiland.org
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nguiland
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/values/image/repository
        value: jcr.nguiland.org/docker-local/org.nguiland.infra/alpine-ops-toolkit
      - op: replace
        path: /spec/values/envMap/ART_OSS_URL
        value: https://oss.nguiland.org/artifactory
    target:
      kind: HelmRelease
      name: artifactory-oss-.*-cleanup
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/values/image/repository
        value: jcr.nguiland.org/docker-local/org.nguiland.infra/alpine-ops-toolkit
    target:
      kind: HelmRelease
      name: artifactory-data-cleanup
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/url
        value: oci://jcr.nguiland.org/docker-local
    target:
      kind: HelmRepository
      name: artifactory-oci
      namespace: infra
