apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ostock-infra
  namespace: infra
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://github.com/biya-bi/ostock-infra.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ostock-infra
  namespace: infra
spec:
  interval: 10m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: ostock-infra
