apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rainbow-infra-helm
  namespace: infra
spec:
  interval: 1m
  url: ssh://github.com/biya-bi/rainbow-infra-helm.git
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  ignore: |
    # Exclude all
    /*
    # Include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-postgres
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/artifactory-postgres
      sourceRef:
        kind: GitRepository
        name: rainbow-infra-helm
      interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-oss
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/artifactory-oss
      sourceRef:
        kind: GitRepository
        name: rainbow-infra-helm
      interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-jcr
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/artifactory-jcr
      sourceRef:
        kind: GitRepository
        name: rainbow-infra-helm
      interval: 10m
