apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rainbow-infra-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/biya-bi/rainbow-infra-secrets.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-age
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m0s
  path: ./dev/sops-age
  prune: true
  sourceRef:
    kind: GitRepository
    name: rainbow-infra-secrets
