apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
  annotations:
    policies.kyverno.io/title: Add imagePullSecrets
    policies.kyverno.io/category: Deployment
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy searches for images coming from the `artifactory-jcr.infra:30000` registry and, if found, will mutate the Pod to add an
      imagePullSecret called `docker-config`.      
spec:
  rules:
  - name: add-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - <(image): "artifactory-jcr.infra:30000/*"
          imagePullSecrets:
          - name: docker-config
