apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: io-utils
  namespace: infra
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ssh-credentials
  url: ssh://github.com/biya-bi/rainbow-io-utils.git
