apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-chart-oci-publish
  namespace: infra
spec:
  providerRef:
    name: helm-chart-oci-publish
  eventSeverity: info
  eventMetadata:
    chartsDir: .
    registry: oci://artifactory-jcr.infra.svc.cluster.local:8082/docker-local
    excludedCharts: artifactory-jcr chart-repository
  eventSources:
    - kind: GitRepository
      name: helm
