apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-chart-oci-publish
  namespace: infra
spec:
  providerRef:
    name: helm-chart-oci-publish
  eventSeverity: info
  eventMetadata:
    helmChartsDir: addons
    helmRegistry: oci://artifactory-jcr.infra.svc.cluster.local:8082/docker-local
  eventSources:
    - kind: GitRepository
      name: nguiland-infra-helm-addons
