apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: infra
data:
  ENVIRONMENT: local
  ACTIFACTORY_JCR_HOST: artifactory-jcr.infra
  ACTIFACTORY_JCR_PORT: "8082"
  ACTIFACTORY_OSS_HOST: artifactory-oss.infra
  ACTIFACTORY_OSS_PORT: "8082"
  ACTIFACTORY_OSS_SCHEME: http
  IMAGE_PULL_ENDPOINT: artifactory-jcr.infra
  IMAGE_PUSH_ENDPOINT: artifactory-jcr.infra
  KEYCLOAK_HOST: keycloak.infra
  OSTOCK_ANGULAR_FRONTEND_HOST: angular-frontend.ostock
  OSTOCK_GATEWAY_SERVICE_HOST: gateway-service.ostock
