apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: docker-build
  namespace: infra
spec:
  type: generic
  address: http://el-docker-build.infra.svc.cluster.local:8080/
