apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: flux-gitrepository-tekton-trigger
  namespace: ${ENVIRONMENT}
spec:
  type: generic
  address: http://flux-gitrepository-tekton-trigger.${ENVIRONMENT}.svc.cluster.local:8080/events
