apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: helm-chart-oci-publish
  namespace: ${ENVIRONMENT}
spec:
  type: generic
  address: http://el-helm-chart-oci-publish.${ENVIRONMENT}.svc.cluster.local:8080/
