apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: maven-lib
  namespace: ${ENVIRONMENT}
spec:
  type: generic
  address: http://el-maven-lib.${ENVIRONMENT}.svc.cluster.local:8080/
