apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-oss-trash-cleanup
  namespace: infra
spec:
  interval: 10m
  dependsOn:
    - name: artifactory-oss
      namespace: infra
  chart:
    spec:
      chart: ./addons/artifactory-oss-trash-cleanup
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: helm-addons
      interval: 10m
  values:
    imagePullEndpoint: artifactory-jcr.infra
    artOssUrl: http://artifactory-oss:8082/artifactory
