apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/postgres
      sourceRef:
        kind: GitRepository
        name: nguiland-infra-helm
      interval: 10m
