apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/git-repositories

patches:
- patch: |-
    - op: replace
      path: /spec/ref/branch
      value: main
  target:
    kind: GitRepository