apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-age
  namespace: infra
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m0s
  path: ./${ENVIRONMENT}/sops-age
  prune: true
  sourceRef:
    kind: GitRepository
    name: nguiland-infra-secrets
    namespace: flux-system
