apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifactory-jcr
  namespace: infra
spec:
  interval: 10m
  chart:
    spec:
      chart: ./core/artifactory-jcr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: artifactory-jcr
      interval: 10m
  values:
    replicaCount: 1
