apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: artifactory-oss
  namespace: infra
spec:
  interval: 1m
  url: ssh://github.com/biya-bi/nguiland-infra-helm.git
  ref:
    branch: develop
  secretRef:
    name: ssh-credentials
  ignore: |
    # Exclude all
    /*
    # Include core directory to allow access to subdirectories
    !/core/
    # Exclude other charts in core
    /core/*
    # Include specific relevant directories
    !/core/artifactory-common/
    !/core/artifactory-oss/
