apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nguiland-infra-helm
  namespace: infra
spec:
  interval: 1m
  url: ssh://github.com/biya-bi/nguiland-infra-helm.git
  ref:
    branch: develop
  secretRef:
    name: ssh-credentials
  ignore: |
    # Exclude all
    /*
    # Include charts directory
    !/charts/
