apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifactory-oci
  namespace: infra
spec:
  type: oci
  url: oci://artifactory-jcr.infra.svc.cluster.local:8082/docker-local
  interval: 5m
  secretRef:
    name: docker-config
