apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: chart-repository
  namespace: ${ENVIRONMENT}
spec:
  url: http://chart-repository.${ENVIRONMENT}.svc.cluster.local/charts
  interval: 5m
