apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../optional

patches:
  - patch: |-
      - op: replace
        path: /spec/values/envMap/SYSTEM_NAMES
        value: jcr oss
    target:
      kind: HelmRelease
      name: artifactory-data-cleanup
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: artifactory-jcr
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: artifactory-oss
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: keycloak
      namespace: infra
