apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../optional

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/mutate/patchStrategicMerge/spec/containers/0/<(image)
        value: "int-jcr.nguiland.org/*"
    target:
      group: kyverno.io
      version: v1
      kind: ClusterPolicy
      name: add-imagepullsecrets
  - patch: |-
      - op: add
        path: /spec/tls/0/hosts/-
        value: int-jcr.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: int-keycloak.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: int-oss.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: int-ostockweb.nguiland.org
      - op: add
        path: /spec/tls/0/hosts/-
        value: int-ostockapi.nguiland.org
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nguiland
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/values/image/repository
        value: int-jcr.nguiland.org/docker-local/org.nguiland.infra/alpine-ops-toolkit
      - op: replace
        path: /spec/values/envMap/ART_OSS_URL
        value: https://int-oss.nguiland.org/artifactory
    target:
      kind: HelmRelease
      name: artifactory-oss-.*-cleanup
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/values/image/repository
        value: int-jcr.nguiland.org/docker-local/org.nguiland.infra/alpine-ops-toolkit
      - op: replace
        path: /spec/values/envMap/SYSTEM_NAMES
        value: jcr oss
    target:
      kind: HelmRelease
      name: artifactory-data-cleanup
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/url
        value: oci://int-jcr.nguiland.org/docker-local
    target:
      kind: HelmRepository
      name: artifactory-oci
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: artifactory-jcr
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: artifactory-oss
      namespace: infra
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: postgres
          namespace: infra
    target:
      kind: HelmRelease
      name: keycloak
      namespace: infra
