apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-chart-oci-publish
  namespace: infra
spec:
  providerRef:
    name: helm-chart-oci-publish
  eventSeverity: info
  eventMetadata:
    chartsDir: addons
    excludedCharts: cronjob-common
    registry: oci://${ACTIFACTORY_JCR_HOST}:${ACTIFACTORY_JCR_PORT}/docker-local
  eventSources:
    - kind: GitRepository
      name: helm
