apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/helm-releases

patches:
- patch: |-
    - op: replace
      path: /spec/values/replicaCount
      value: 2
  target:
    kind: HelmRelease
