apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./overlays/dev
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: ostock
    namespace: infra
- patch: |-
    - op: replace
      path: /spec/path
      value: ./dev/sops-age
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: sops-age
    namespace: infra
- patch: |-
    - op: replace
      path: /data/image-pull-endpoint
      value: jcr.nguiland.org
  target:
    version: v1
    kind: ConfigMap
    name: env-settings
    namespace: infra
- patch: |-
    - op: replace
      path: /spec/rules/0/mutate/patchStrategicMerge/spec/containers/0/<(image)
      value: "jcr.nguiland.org/*"
  target:
    group: kyverno.io
    version: v1
    kind: ClusterPolicy
    name: add-imagepullsecrets
