apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/mutate/patchStrategicMerge/spec/containers/0/<(image)
        value: "jcr.nguiland.org/*"
    target:
      group: kyverno.io
      version: v1
      kind: ClusterPolicy
      name: add-imagepullsecrets
  - patch: |-
      - op: replace
        path: /spec/values/image/repository
        value: dev-jcr.nguiland.org/docker-local/org.nguiland.infra/alpine-ops-toolkit
    target:
      kind: HelmRelease
      name: artifactory-data-cleanup
      namespace: infra
  - patch: |-
      - op: replace
        path: /spec/url
        value: oci://dev-jcr.nguiland.org/docker-local
    target:
      kind: HelmRepository
      name: artifactory-oci
      namespace: infra
