apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./overlays/local
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: ostock
    namespace: infra
- patch: |-
    - op: replace
      path: /spec/path
      value: ./local/sops-age
  target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: sops-age
    namespace: infra
- patch: |-
    - op: remove
      path: /spec/rules/2
    - op: remove
      path: /spec/rules/1
    - op: replace
      path: /spec/rules/0/host
      value: artifactory-jcr.infra
    - op: remove
      path: /spec/tls
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: nguiland
    namespace: infra
