apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-jcr-config
  namespace: ${ENVIRONMENT}
data:
  artifactory.config.import.yml: |
    GeneralConfiguration:
      eula:
        accepted: true
    OnboardingConfiguration:
      repoTypes:
        - docker
