apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-oss-config
  namespace: infra
data:
  artifactory.config.import.yml: |
    GeneralConfiguration:
      eula:
        accepted: true
    OnboardingConfiguration:
      repoTypes:
        - maven
